name: jaguar_orm
description: Source-generated ORM with relations (one-to-one, one-to-many, many-to-many), preloading, cascading, polymorphic relations, etc
version: 2.2.7
authors:
  - Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_orm
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  jaguar_query: # ^2.2.9
    git:
      # url: https://github.com/Jaguar-dart/jaguar_orm.git
      url: https://github.com/u007/jaguar_orm.git
      ref: legacyV3
      path: query
  quiver: ^2.0.5
  path: ^1.6.4
  meta: ^1.1.7

dev_dependencies:
  test: ^1.9.4
  jaguar_query_postgres: # ^0.2.5
    path: ../postgres
